### ISSUE TITLE
[Feature] Add support for condition checking in the library as well.

### ISSUE THREAD

**Issue by Vishal-Chdhry** [nirmata/kyverno-notation-verifier#2]
Currently, we are returning a list of all the attestations and images in the response as follows
```json
{
  "verified": true,
  "message": "...",
  "images": [
      {
         "name": "container1",
         "path":  "/spec/containers/0",
         "image":  "ghcr.io/kyverno/test-verify-image@sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105",
      } 
  ],
  "attestations": [
      {
        "type": "sbom/cyclone-dx",
        "payload": "the entire SBOM",
        "image":  "ghcr.io/kyverno/test-verify-image@sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105"
      }
  ]
}
``` 

Since we are not doing parallel processing of images, it can take a lot of time to verify so many attestations and return a payload and if one of the condition checks fails, all this effort will be wasted.

We can add conditions to the policy so the condition is checked while the attestation is verified, and the verification will stop when condition checking fails.

We can use the following structure

```yaml
context:
- name: response
  apiCall:
    method: POST
    data:
    - key: images
      value: "{{ images }}"
    - key: attestations
      value:
        - imageReference: "*"
          type: 
            - name: sbom/cyclone-dx
              key: "{{ element.components[].licenses[].expression }}"
              operator: AllNotIn
              value: ["GPL-2.0", "GPL-3.0"]
            - name: application/sarif+json
              key: "{{ element.components[].licenses[].expression }}"
              operator: AllNotIn
              value: ["GPL-2.0", "GPL-3.0"]
        - imageReference: "844333597536.dkr.ecr.us-west-2.amazonaws.com/kyverno-demo:*"
          type:
            - name: application/vnd.cyclonedx
              key: "{{ element.components[].licenses[].expression }}"
              operator: AllNotIn
              value: ["GPL-2.0", "GPL-3.0"]
    service:
      url: https://svc.kyverno-notation-aws/checkimages
      caBundle: |-
...
```
